<?php

  namespace Controllers;


  use Models\User;

  class LoginController extends User
  {
    public function getLoggedUser($email, $password)
    {
      return $this->login($email, $password);
    }

/*    public function checkEmailExists($email): bool
    {
      return parent::checkEmailExists($email); // TODO: Change the autogenerated stub
    }*/

    public function setSessionLoginError()
    {
      $errors = $this->getErrorData();
//      session_start();
      $_SESSION['login_errors'] = $errors;
//      var_dump($errors);
    }

  }